spring:
  datasource:
    url: jdbc:mysql://pixcer.top:3306/mlnlco-platform?characterEncoding=utf8&TimeZone=Asia/Shanghai
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      max-lifetime: 120000

  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
#
#  profile 开启 ....
#  profiles:
#    active: dev
logging:
  level:
    org.hibernate: INFO
    org.hibernate.type.descriptor.sql.BasicBinder: INFO
    org.hibernate.type.descriptor.sql.BasicExtractor: INFO
